spring:
  datasource:
    url: jdbc:mysql://localhost:3307/seas_backend
    username: root
    password: Selfgoma9

#     url: jdbc:mysql://avnadmin:AVNS_RBjhUbbzClUsmK3Wo0i@seas-backend-seas.b.aivencloud.com:28365/defaultdb?ssl-mode=REQUIRED
#     username: avnadmin
#     password: AVNS_RBjhUbbzClUsmK3Wo0i

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 465
    username: app.todolis@gmail.com
    password: wltpbbvqpguwmyqh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        starttls:
          enable: true
    protocol: smtp
server:
  port: 8053


