name: SEAS CICD Flow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tumbwe/seas-backend .

      - name: Publish image to Docker Hub
        run: docker push tumbwe/seas-backend:latest

  deploy:
    needs: build
    runs-on: [ self-hosted ]

    steps:
      - name: Install Docker
        run: |
          if ! command -v docker &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y docker.io
              fi
      - name: Pull image from Docker Hub
        run: sudo docker pull tumbwe/seas-backend:latest

      - name: Stop and remove old container if exists
        run: |
          sudo docker rm -f seas-api-container || true
          sudo systemctl restart docker

      - name: Run new container
        run: sudo docker run -d -p 8088:8088 --name seas-api-container tumbwe/seas-backend

      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
